DROP TABLE IF EXISTS EXAMS ;
CREATE TABLE EXAMS (
  ID int NOT NULL,
  Student_ID int NOT NULL,
  Subject_ID int NOT NULL,
  Grade int NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (Student_ID) REFERENCES STUDENTS(ID),
  FOREIGN KEY (Subject_ID) REFERENCES SUBJECTS(ID)
);