DROP TABLE IF EXISTS SUBJECTS ;
CREATE TABLE SUBJECTS (
  ID int,
  PRIMARY KEY (ID)
);

INSERT INTO subjects(Name) VALUES('History');
INSERT INTO subjects(Name) VALUES('Math');
INSERT INTO subjects(Name) VALUES('Biology');